[package]
name = "dgc_ecs"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
# dgc_alloc = { path = "../dgc_alloc" }
thiserror = { workspace = true }
# tidy-alphabetical-end
