name: CD

on:
  workflow_run:
    workflows: [ "CI" ]
    branches: [ "master" ]
    types:
      - completed

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Prepare Rustup target
        run: rustup target add x86_64-unknown-linux-gnu --toolchain stable
      - name: Build release binary
        run: cargo build --release --target x86_64-unknown-linux-gnu
      - name: Prepare release artifact
        run: |
          sudo mkdir dist
          sudo apt-get install zip
          sudo zip -rv -D -9 dist/Linux.zip target/x86_64-unknown-linux-gnu/release/racket-rs

      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: Linux.zip
          path: dist/
          if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - name: Release
        uses: actions/setup-node@4
        with:
          node-version: lts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

